<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Tickwire.Persistence\Tickwire.Persistence.csproj" />
    <ProjectReference Include="..\Tickwire.LogAnalyzer\Tickwire.LogAnalyzer.csproj" />
    <ProjectReference Include="..\Tickwire.Fix.Session\Tickwire.Fix.Session.csproj" />
    <ProjectReference Include="..\Tickwire.Engine\Tickwire.Engine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
  </ItemGroup>

  <PropertyGroup>
  </PropertyGroup>

</Project>
