// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tickwire.Persistence;

#nullable disable

namespace Tickwire.Persistence.Migrations
{
    [DbContext(typeof(TickwireDbContext))]
    [Migration("20260930201809_ArchiveRetentionIndex")]
    partial class ArchiveRetentionIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Tickwire.Persistence.AuditEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Details")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Tickwire.Persistence.ClientEntity", b =>
                {
                    b.Property<string>("ClientId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("KillSwitch")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OwnerTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("ClientId");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Tickwire.Persistence.ExecutionEntity", b =>
                {
                    b.Property<string>("ExecId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ClOrdID")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<decimal?>("Commission")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CumQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ExecType")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("LastMkt")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<decimal>("LastPx")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("LastQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("LeavesQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("OrdStatus")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<long>("OrderKey")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("TransactTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ExecId");

                    b.HasIndex("OrderKey");

                    b.ToTable("executions", (string)null);
                });

            modelBuilder.Entity("Tickwire.Persistence.FixSessionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BeginString")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("ClientCompId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EnableChaos")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("HeartBtInt")
                        .HasColumnType("int");

                    b.Property<bool>("ResetOnLogon")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("trading");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("VenueCompId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("BeginString", "ClientCompId", "VenueCompId")
                        .IsUnique();

                    b.ToTable("fix_sessions", (string)null);
                });

            modelBuilder.Entity("Tickwire.Persistence.OrderEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("AvgPx")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("ClOrdID")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CumQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("LeavesQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("OrdType")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<decimal>("OrderQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("OrigClOrdID")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Text")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("TimeInForce")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "CreatedAt");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Tickwire.Persistence.RiskLimitsEntity", b =>
                {
                    b.Property<string>("ClientId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("AllowedOrderTypes")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("AllowedTimeInForce")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("AllowedUnderlyings")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("CancelOnDisconnect")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("MaxAbsDelta")
                        .HasColumnType("double");

                    b.Property<double>("MaxAbsVega")
                        .HasColumnType("double");

                    b.Property<int>("MaxMessagesPerSecond")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxNotional")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaxOpenOrders")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxOrderQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PriceBandMinAbs")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PriceBandPct")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ClientId");

                    b.ToTable("risk_limits", (string)null);
                });

            modelBuilder.Entity("Tickwire.Persistence.SessionMessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<bool>("IsStore")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MsgType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<byte[]>("Raw")
                        .IsRequired()
                        .HasColumnType("varbinary(8192)");

                    b.Property<int>("SeqNum")
                        .HasColumnType("int");

                    b.Property<string>("SessionKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IsStore", "Timestamp");

                    b.HasIndex("SessionKey", "Timestamp");

                    b.HasIndex("SessionKey", "IsStore", "SeqNum");

                    b.ToTable("session_messages", (string)null);
                });

            modelBuilder.Entity("Tickwire.Persistence.SessionStateEntity", b =>
                {
                    b.Property<string>("SessionKey")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NextSenderSeqNum")
                        .HasColumnType("int");

                    b.Property<int>("NextTargetSeqNum")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SessionKey");

                    b.ToTable("session_state", (string)null);
                });

            modelBuilder.Entity("Tickwire.Persistence.FixSessionEntity", b =>
                {
                    b.HasOne("Tickwire.Persistence.ClientEntity", null)
                        .WithMany("Sessions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tickwire.Persistence.RiskLimitsEntity", b =>
                {
                    b.HasOne("Tickwire.Persistence.ClientEntity", null)
                        .WithOne("Limits")
                        .HasForeignKey("Tickwire.Persistence.RiskLimitsEntity", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tickwire.Persistence.ClientEntity", b =>
                {
                    b.Navigation("Limits");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
