<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Tickwire.Fix\Tickwire.Fix.csproj" />
    <ProjectReference Include="..\Tickwire.Venue\Tickwire.Venue.csproj" />
    <ProjectReference Include="..\Tickwire.Pricing\Tickwire.Pricing.csproj" />
    <ProjectReference Include="..\Tickwire.Fix.Session\Tickwire.Fix.Session.csproj" />
  </ItemGroup>

  <PropertyGroup>
  </PropertyGroup>

</Project>
